/**
 * This code generated by CodeGenerator<ptma@163.com>
 */
package com.hy.model;


/**
 * <p>实体类</p>
 * <p>Table: tb_user - </p>
 *
 * @since 2018-06-10 07:07:41
 */
public class TbUser {

    /** id -  */
    private Integer id;
    /** user_name -  */
    private String userName;
    /** password -  */
    private String password;
    /** description -  */
    private String description;


    public Integer getId(){
        return this.id;
    }
    public void setId(Integer id){
        this.id = id;
    }

    public String getUserName(){
        return this.userName;
    }
    public void setUserName(String userName){
        this.userName = userName;
    }

    public String getPassword(){
        return this.password;
    }
    public void setPassword(String password){
        this.password = password;
    }

    public String getDescription(){
        return this.description;
    }
    public void setDescription(String description){
        this.description = description;
    }
}