server:
  port: 8080
  servlet:
    context-path: /springboot-jpa

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.213.128:3306/test1?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
      hibernate:
        ddl-auto: create  # 第一次简表create  后面用update
      show-sql: true
      properties:
        hibernate :
          dialect : org.hibernate.dialect.MySQL5InnoDBDialect

