/**
 * This code generated by CodeGenerator<ptma@163.com>
 */
package com.hy.model;

import java.util.Date;

import org.apache.ibatis.type.Alias;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * <p>实体类</p>
 * <p>Table: user - 用户表</p>
 *
 * @since 2018-10-01 07:48:51
 */
public class User {

    /** id - 数据库主键 */
    private Long id;
    /** user_code - 平台用户编号 */
    private String userCode;
    /** mobile - 手机号 */
    private String mobile;
    /** password - 登录密码 */
    private String password;
    /** gesture_password - 手势密码 */
    private Integer gesturePassword;
    /** type - 用户类型： 1:普通用户 2:企业用户 */
    private Byte type;
    /** status - 状态 1:正常 2:锁定 */
    private Byte status;
    /** open_account_status - 开户状态 1:未开户 3:已开户 4:待激活（汇付开户，已绑卡，未设置交易密码） 5:已开户未绑卡 */
    private Byte openAccountStatus;
    /** platform - 平台 */
    private String platform;
    /** client - 客户端 1pc 2微信 3iOS 4安卓 */
    private Byte client;
    /** version - 版本号 */
    private String version;
    /** channal - 渠道 */
    private Integer channal;
    /** register_code - 注册时使用的邀请码 */
    private String registerCode;
    /** register_ip - 注册IP */
    private Long registerIp;
    /** last_login_time - 上一次登录时间 */
    private Date lastLoginTime;
    /** last_login_ip - 上一次登录IP */
    private Long lastLoginIp;
    /** create_time - 创建时间 */
    private Date createTime;
    /** update_time - 更新时间 */
    private Date updateTime;
    /** nickname - 昵称 */
    private String nickname;
    /** openid - openid */
    private String openid;
    /** city - 城市 */
    private String city;
    /** headimgurl - 头像URL */
    private String headimgurl;


    public Long getId(){
        return this.id;
    }
    public void setId(Long id){
        this.id = id;
    }

    public String getUserCode(){
        return this.userCode;
    }
    public void setUserCode(String userCode){
        this.userCode = userCode;
    }

    public String getMobile(){
        return this.mobile;
    }
    public void setMobile(String mobile){
        this.mobile = mobile;
    }

    public String getPassword(){
        return this.password;
    }
    public void setPassword(String password){
        this.password = password;
    }

    public Integer getGesturePassword(){
        return this.gesturePassword;
    }
    public void setGesturePassword(Integer gesturePassword){
        this.gesturePassword = gesturePassword;
    }

    public Byte getType(){
        return this.type;
    }
    public void setType(Byte type){
        this.type = type;
    }

    public Byte getStatus(){
        return this.status;
    }
    public void setStatus(Byte status){
        this.status = status;
    }

    public Byte getOpenAccountStatus(){
        return this.openAccountStatus;
    }
    public void setOpenAccountStatus(Byte openAccountStatus){
        this.openAccountStatus = openAccountStatus;
    }

    public String getPlatform(){
        return this.platform;
    }
    public void setPlatform(String platform){
        this.platform = platform;
    }

    public Byte getClient(){
        return this.client;
    }
    public void setClient(Byte client){
        this.client = client;
    }

    public String getVersion(){
        return this.version;
    }
    public void setVersion(String version){
        this.version = version;
    }

    public Integer getChannal(){
        return this.channal;
    }
    public void setChannal(Integer channal){
        this.channal = channal;
    }

    public String getRegisterCode(){
        return this.registerCode;
    }
    public void setRegisterCode(String registerCode){
        this.registerCode = registerCode;
    }

    public Long getRegisterIp() {
        return registerIp;
    }

    public void setRegisterIp(Long registerIp) {
        this.registerIp = registerIp;
    }

    public Long getLastLoginIp() {
        return lastLoginIp;
    }

    public void setLastLoginIp(Long lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    public Date getLastLoginTime(){
        return this.lastLoginTime;
    }
    public void setLastLoginTime(Date lastLoginTime){
        this.lastLoginTime = lastLoginTime;
    }

    public Date getCreateTime(){
        return this.createTime;
    }
    public void setCreateTime(Date createTime){
        this.createTime = createTime;
    }

    public Date getUpdateTime(){
        return this.updateTime;
    }
    public void setUpdateTime(Date updateTime){
        this.updateTime = updateTime;
    }

    public String getNickname(){
        return this.nickname;
    }
    public void setNickname(String nickname){
        this.nickname = nickname;
    }

    public String getOpenid(){
        return this.openid;
    }
    public void setOpenid(String openid){
        this.openid = openid;
    }

    public String getCity(){
        return this.city;
    }
    public void setCity(String city){
        this.city = city;
    }

    public String getHeadimgurl(){
        return this.headimgurl;
    }
    public void setHeadimgurl(String headimgurl){
        this.headimgurl = headimgurl;
    }
}