/**
 * This code generated by CodeGenerator<ptma@163.com>
 */
package com.hy.dao;


import com.hy.model.User;

import java.util.List;

/**
 * <p>Mapper接口</p>
 * <p>Table: user - 用户表</p>
 * @since 2018-10-01 07:48:51
 */

public interface UserMapper {
	/**
	 *保存,未经校验,禁止直接调用
	 */
	void save(User model);
	
	/**
	 *获取单个对象,未经校验,禁止直接调用
	 */
	User getByCondition(User model);
	
	/**
	 *查询多个对象,未经校验,禁止直接调用
	 */
	List<User> getListByCondition(User model);


	List<User> getListByConditionLike(User model);
	
	/**
	 *修改,未经校验,禁止直接调用
	 */
	Integer update(User model);

	/**
	 *分页查询,未经校验,禁止直接调用
	 */
	List<User> getPageList(User model);

	/**
	 *获取总记录数,未经校验,禁止直接调用
	 */
	Long totalSize(User model);
}